package segment

type Logo struct {
	Default string `json:"default"`
	Mark    string `json:"mark"`
	Alt     string `json:"alt"`
}

type Pagination struct {
	Current      string  `json:"current"`
	Next         *string `json:"next,omitempty"`
	TotalEntries int     `json:"totalEntries"`
}

type IntegrationOption struct {
	Name         string `json:"name"`
	Type         string `json:"type"`
	Required     bool   `json:"required"`
	Description  string `json:"description"`
	DefaultValue string `json:"defaultValue"`
	Label        string `json:"label"`
}

var (
	SourceSlugs = []string{
		"active-campaign",
		"adwords",
		"aircall",
		"airship",
		"amazon-s3",
		"amp",
		"amplitude-cohorts",
		"android",
		"autopilothq",
		"beamer",
		"blueshift",
		"braze",
		"candu",
		"chatlio",
		"clojure",
		"customerio",
		"delighted",
		"drip",
		"facebook-ads",
		"facebook-lead-ads",
		"factual-engine",
		"foursquare-pilgrim",
		"friendbuy",
		"go",
		"herow",
		"http-api",
		"hubspot",
		"intercom",
		"ios",
		"iterable",
		"java",
		"javascript",
		"klaviyo",
		"klenty",
		"kotlin",
		"kotlin-android",
		"launchdarkly",
		"leanplum",
		"looker",
		"mailchimp",
		"mailjet",
		"mandrill",
		"marketo",
		"mixpanel-cohorts-source",
		"moesif-api-analytics",
		"net",
		"node.js",
		"nudgespot",
		"pendo",
		"php",
		"pixel-tracking-api",
		"project",
		"provesource",
		"python",
		"radar",
		"react-native",
		"refiner",
		"regal-voice",
		"roku",
		"ruby",
		"salesforce",
		"salesforce-marketing-cloud",
		"selligent-marketing-cloud",
		"sendgrid",
		"shopify-littledata",
		"snowflake",
		"stripe",
		"swift",
		"twilio",
		"twilio-event-streams",
		"vero",
		"wootric",
		"xamarin",
		"youbora",
		"zendesk",
	}
	WarehouseSlugs = []string{
		"azuresqldb",
		"azuresqldw",
		"bigquery",
		"db2",
		"postgres",
		"redshift",
		"snowflake",
	}
	DestinationSlugs = []string{
		"adroll",
		"appsflyer",
		"alexa",
		"amplitude",
		"adwords",
		"adlearn-open-platform",
		"appnexus",
		"attribution",
		"bing-ads",
		"bronto",
		"bugherd",
		"bugsnag",
		"chartbeat",
		"comscore",
		"clicky",
		"crittercism",
		"convertro",
		"countly",
		"curebit",
		"crazy-egg",
		"customer.io",
		"drip",
		"email-aptitude",
		"eloqua",
		"errorception",
		"flurry",
		"foxmetrics",
		"gainsight",
		"gauges",
		"fullstory",
		"google-tag-manager",
		"gosquared",
		"google-analytics",
		"hello-bar",
		"heap",
		"hittail",
		"help-scout",
		"improvely",
		"hubspot",
		"quanticmind",
		"inspectlet",
		"indicative",
		"iron.io",
		"intercom",
		"kissmetrics",
		"klaviyo",
		"keen-io",
		"iterable",
		"librato",
		"leanplum",
		"livechat",
		"localytics",
		"lucky-orange",
		"lytics",
		"mailchimp",
		"mediamath",
		"millennial-media",
		"mixpanel",
		"tune",
		"mouseflow",
		"navilytics",
		"olark",
		"nanigans",
		"monetate",
		"mousestats",
		"new-relic",
		"pardot",
		"optimizely",
		"outbound",
		"perfect-audience",
		"pingdom",
		"piwik",
		"qualaroo",
		"quantcast",
		"rollbar",
		"salesforce",
		"sentry",
		"shareasale",
		"spinnakr",
		"taplytics",
		"snapengage",
		"tapstream",
		"track-js",
		"totango",
		"tv-squared",
		"twitter-ads",
		"uservoice",
		"visual-website-optimizer",
		"webengage",
		"vero",
		"webhooks",
		"woopra",
		"zendesk",
		"yandex-metrica",
		"kahuna",
		"blueshift",
		"xplenty",
		"nudgespot",
		"natero",
		"atatus",
	}
)
